# Generated by Django 3.0.2 on 2020-07-17 19:39

from django.db import migrations, models
import django.db.models.deletion
import src.core.models.base
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('host_ip', models.CharField(blank=True, max_length=700, null=True, verbose_name='Host IP')),
                ('host_local_ip', models.CharField(blank=True, max_length=700, null=True, verbose_name='Host local IP')),
                ('host_name', models.CharField(blank=True, max_length=700, null=True, verbose_name='Host Name')),
                ('host_arch', models.CharField(blank=True, max_length=700, null=True, verbose_name='Host Arch')),
                ('host_domain', models.CharField(blank=True, max_length=700, null=True, verbose_name='Host Domain')),
                ('host_username', models.CharField(blank=True, max_length=700, null=True, verbose_name='Host Name')),
            ],
            options={
                'verbose_name': 'Machine',
                'verbose_name_plural': 'Machines',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='DumpedCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('guid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This field is automatically determined by the system, do not interfere.', unique=True, verbose_name='Unique ID')),
                ('ticketfile', models.FileField(blank=True, null=True, upload_to=src.core.models.base._handle_file, verbose_name='Ticket File')),
                ('type', models.CharField(choices=[('HASH', 'Dumped Hash'), ('NORMAL', 'Clear Text'), ('TICKET', 'Dumped Ticket')], default='NORMAL', max_length=32, verbose_name='Credential Type')),
                ('username', models.CharField(blank=True, max_length=700, null=True, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=700, null=True, verbose_name='Password/Secret')),
                ('machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Machine')),
            ],
            options={
                'verbose_name': 'Dumped Credentials',
                'verbose_name_plural': 'Dumped Credentials',
                'ordering': ('-created',),
            },
        ),
    ]
